openapi: "3.0"
info:
  version: 1.0.0
  title: CLI configuration
host: "app.zegami.com"
type: object
properties:
    # Data set config
  dataset_type:
    type: string # enums are further down, dont need to repeat here
  file_config:
    type: object
    properties:
      recursive:
        type: boolean
      mime_type:
        type: string
        pattern: ^[-\w.]+/[-\w.]+$
      path:
        type: string
        pattern: \.(tab|tsv|csv|xlsx)$
      directory:
        type: string
      paths:
        type: array
        items:
          type: string
  sql_config:
    type: object
    properties:
      connection:
        type: string
      query:
        type: string
    required:
    - connection
    - query
  # Image set config
  imageset_type:
    type: string # enums are further down, dont need to repeat here
  collection_id:
    type: string
    pattern: ^[0-9a-fA-F]{24}$
  dataset_id:
    type: string
    pattern: ^[0-9a-fA-F]{24}$
  dataset_column:
    type: string
  # publish collection config
  update_type:
    type: string
    enum:
    - publish
    - imageset_update
    - dataset_update
    - collection_create
  publish_config:
    type: object
    properties:
      publish:
        type: boolean
      destination_project:
        type: string
    required:
    - publish
    - destination_project
definitions:
  collection:
    properties:
      name:
        type: string
        description: name for the collection
      description:
        type: string
        description: descriptive text for the collection
  file_dataset:
    properties:
      dataset_type:
        enum:
        - file
      file_config:
        oneOf:
        - required:
          - path
        - required:
          - directory
    required:
    - file_config
  sql_dataset:
    properties:
      dataset_type:
        enum:
        - sql
    required:
    - sql_config
  file_imageset_properties:
    properties:
      imageset_type:
        enum:
        - file
      file_config:
        required:
        - paths
  url_imageset_properties:
    properties:
      imageset_type:
        enum:
        - url
      url_template:
        type: string
  azure_storage_container_properties:
    properties:
      imageset_type:
        enum:
        - azure_storage_container
      container_name:
        type: string
anyOf:
# dataset only
- oneOf:
  - allOf:
    - $ref: '#/definitions/file_dataset'
    - required:
      - dataset_type
      - file_config
  - allOf:
    - $ref: '#/definitions/sql_dataset'
    - required:
      - dataset_type
      - sql_config
# imageset only
- oneOf:
  - allOf:
    - $ref: '#/definitions/file_imageset_properties'
    - required:
      - file_config
      - collection_id
      - dataset_id
      - dataset_column
      - imageset_type
  - allOf:
    - $ref: '#/definitions/url_imageset_properties'
    - required:
      - collection_id
      - dataset_id
      - dataset_column
      - imageset_type
  - allOf:
    - $ref: '#/definitions/azure_storage_container_properties'
    - required:
      - collection_id
      - dataset_id
      - dataset_column
      - imageset_type
      - container_name
# collection create should have a name and contain all configuration but no ids
- allOf:
  - $ref: '#/definitions/collection'
  - oneOf:
    - allOf:
      - $ref: '#/definitions/file_dataset'
      - required:
        - dataset_type
        - file_config
    - allOf:
      - $ref: '#/definitions/sql_dataset'
      - required:
        - dataset_type
        - sql_config
  - oneOf:
    - allOf:
      - $ref: '#/definitions/file_imageset_properties'
      - required:
        - file_config
        - dataset_column
        - imageset_type
    - allOf:
      - $ref: '#/definitions/url_imageset_properties'
      - required:
        - dataset_column
        - imageset_type
    - allOf:
      - $ref: '#/definitions/azure_storage_container_properties'
      - required:
        - dataset_column
        - imageset_type
        - container_name
# collection publish stuff
- oneOf:
  - properties:
      update_type:
        enum:
        - publish
    required:
    - publish_config
    - update_type
